### ISSUE TITLE
Executor UI Improvements/Ideas

### ISSUE THREAD

**Issue by thunderfurry** [atlas-developers/atlas#2]
### **IT DOESN'T MATTER WHAT THE UI IS, JUST HAVE CURVED EDGES PLEASE**
anyways do you guys like this design i made 
![image](https://user-images.githubusercontent.com/91995526/213672728-ce93b861-7705-433a-b6d1-205f669201cf.png)

(themes custom syntax colors, custom bg wallpapers, and colors)

**Comment by atlas-developers** [comment]
Thanks for leaving an issue! Your design will be incorporated into the executor, but please don't start issues here for the executor. This repository is for the website.
